http:
  address: ":8080"
  workers:
    command: "php roadrunner/index.php"
    relay: "unix:///tmp/rr.socket"
    pool:
      numWorkers: 1
      maxJobs: 1
reload:
  enabled: true
  services:
    http:
      recursive: true
      ignore: [ "vendor" ]
      patterns: [ ".php", ".go", ".md" ]
      dirs:     [ "." ]


static:
  dir: "public"
